[unstable]
json-target-spec = true
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-TESTOS3.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"